/**
 * Structural definitions for equipment-type SEO landing pages.
 * Copy lives in equipmentLandingCopy.js — keep filters/paths/brands here.
 */

import { getBrandLogoMeta } from './brandCatalogueCore.js'
import { LANDING_PATHS } from './landingPagePaths.js'

const C = 'full_commercial'
const H = 'home_use'

function brands(...slugs) {
  return Object.freeze(slugs.filter((slug) => Boolean(getBrandLogoMeta(slug))))
}

/** @typedef {'commercial-cardio'|'commercial-strength'|'home-cardio'|'home-strength'} EquipmentCluster */

/**
 * @typedef {object} EquipmentLandingDef
 * @property {string} id
 * @property {string} path
 * @property {EquipmentCluster} cluster
 * @property {string} parentPath
 * @property {string} parentName
 * @property {'full_commercial'|'home_use'} rating
 * @property {string[]} [categorySlugs]
 * @property {string} [search]
 * @property {('title'|'brand'|'model'|'description')[]} [searchIn]
 * @property {string[]} [excludeTitleIncludes]
 * @property {string[]} featuredBrandSlugs
 * @property {{ id: string, label: string, description: string, to: string }[]} neighborCategories
 */

const RAW_DEFS = [
  {
    id: 'used-commercial-treadmills',
    path: '/used-commercial-treadmills',
    cluster: 'commercial-cardio',
    parentPath: LANDING_PATHS.commercialCardio,
    parentName: 'Commercial Cardio Equipment',
    rating: C,
    categorySlugs: ['treadmill'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'technogym',
      'matrix-fitness',
      'precor',
      'cybex',
      'woodway',
      'spirit-fitness',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'cross', label: 'Commercial Cross Trainers', description: 'Facility-grade ellipticals', to: '/used-commercial-cross-trainers' },
      { id: 'bikes', label: 'Commercial Exercise Bikes', description: 'Upright and recumbent bikes', to: '/used-commercial-exercise-bikes' },
      { id: 'stair', label: 'Commercial Stair Climbers', description: 'Stepmills and climbing cardio', to: '/used-commercial-stair-climbers' },
      { id: 'rowers', label: 'Commercial Rowing Machines', description: 'Air, magnetic and water rowers', to: '/used-commercial-rowing-machines' },
      { id: 'spin', label: 'Commercial Indoor Cycles', description: 'Studio and spin bikes', to: '/used-commercial-indoor-cycles' },
      { id: 'hub', label: 'All Commercial Cardio', description: 'Browse the full commercial cardio hub', to: LANDING_PATHS.commercialCardio },
    ],
  },
  {
    id: 'used-commercial-exercise-bikes',
    path: '/used-commercial-exercise-bikes',
    cluster: 'commercial-cardio',
    parentPath: LANDING_PATHS.commercialCardio,
    parentName: 'Commercial Cardio Equipment',
    rating: C,
    categorySlugs: ['upright-bikes', 'recumbent-bikes'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'technogym',
      'matrix-fitness',
      'precor',
      'cybex',
      'spirit-fitness',
      'schwinn',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Commercial Treadmills', description: 'Facility-grade running decks', to: '/used-commercial-treadmills' },
      { id: 'spin', label: 'Commercial Indoor Cycles', description: 'Studio and spin bikes', to: '/used-commercial-indoor-cycles' },
      { id: 'cross', label: 'Commercial Cross Trainers', description: 'Ellipticals for high throughput', to: '/used-commercial-cross-trainers' },
      { id: 'rowers', label: 'Commercial Rowing Machines', description: 'Air, magnetic and water rowers', to: '/used-commercial-rowing-machines' },
      { id: 'stair', label: 'Commercial Stair Climbers', description: 'Stepmills and climbing cardio', to: '/used-commercial-stair-climbers' },
      { id: 'hub', label: 'All Commercial Cardio', description: 'Browse the full commercial cardio hub', to: LANDING_PATHS.commercialCardio },
    ],
  },
  {
    id: 'used-commercial-cross-trainers',
    path: '/used-commercial-cross-trainers',
    cluster: 'commercial-cardio',
    parentPath: LANDING_PATHS.commercialCardio,
    parentName: 'Commercial Cardio Equipment',
    rating: C,
    categorySlugs: ['crosstrainers'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'technogym',
      'precor',
      'matrix-fitness',
      'cybex',
      'spirit-fitness',
      'horizon-fitness',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Commercial Treadmills', description: 'Facility-grade running decks', to: '/used-commercial-treadmills' },
      { id: 'bikes', label: 'Commercial Exercise Bikes', description: 'Upright and recumbent bikes', to: '/used-commercial-exercise-bikes' },
      { id: 'rowers', label: 'Commercial Rowing Machines', description: 'Air, magnetic and water rowers', to: '/used-commercial-rowing-machines' },
      { id: 'stair', label: 'Commercial Stair Climbers', description: 'Stepmills and climbing cardio', to: '/used-commercial-stair-climbers' },
      { id: 'spin', label: 'Commercial Indoor Cycles', description: 'Studio and spin bikes', to: '/used-commercial-indoor-cycles' },
      { id: 'hub', label: 'All Commercial Cardio', description: 'Browse the full commercial cardio hub', to: LANDING_PATHS.commercialCardio },
    ],
  },
  {
    id: 'used-commercial-rowing-machines',
    path: '/used-commercial-rowing-machines',
    cluster: 'commercial-cardio',
    parentPath: LANDING_PATHS.commercialCardio,
    parentName: 'Commercial Cardio Equipment',
    rating: C,
    categorySlugs: ['rowers'],
    featuredBrandSlugs: brands(
      'concept2',
      'waterrower',
      'technogym',
      'life-fitness',
      'matrix-fitness',
      'spirit-fitness',
      'pulse-fitness',
      'wattbike',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Commercial Treadmills', description: 'Facility-grade running decks', to: '/used-commercial-treadmills' },
      { id: 'bikes', label: 'Commercial Exercise Bikes', description: 'Upright and recumbent bikes', to: '/used-commercial-exercise-bikes' },
      { id: 'cross', label: 'Commercial Cross Trainers', description: 'Ellipticals for high throughput', to: '/used-commercial-cross-trainers' },
      { id: 'stair', label: 'Commercial Stair Climbers', description: 'Stepmills and climbing cardio', to: '/used-commercial-stair-climbers' },
      { id: 'spin', label: 'Commercial Indoor Cycles', description: 'Studio and spin bikes', to: '/used-commercial-indoor-cycles' },
      { id: 'hub', label: 'All Commercial Cardio', description: 'Browse the full commercial cardio hub', to: LANDING_PATHS.commercialCardio },
    ],
  },
  {
    id: 'used-commercial-stair-climbers',
    path: '/used-commercial-stair-climbers',
    cluster: 'commercial-cardio',
    parentPath: LANDING_PATHS.commercialCardio,
    parentName: 'Commercial Cardio Equipment',
    rating: C,
    categorySlugs: ['stairclimbers'],
    featuredBrandSlugs: brands(
      'stairmaster',
      'matrix-fitness',
      'life-fitness',
      'technogym',
      'cybex',
      'spirit-fitness',
      'precor',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Commercial Treadmills', description: 'Facility-grade running decks', to: '/used-commercial-treadmills' },
      { id: 'cross', label: 'Commercial Cross Trainers', description: 'Ellipticals for high throughput', to: '/used-commercial-cross-trainers' },
      { id: 'bikes', label: 'Commercial Exercise Bikes', description: 'Upright and recumbent bikes', to: '/used-commercial-exercise-bikes' },
      { id: 'rowers', label: 'Commercial Rowing Machines', description: 'Air, magnetic and water rowers', to: '/used-commercial-rowing-machines' },
      { id: 'spin', label: 'Commercial Indoor Cycles', description: 'Studio and spin bikes', to: '/used-commercial-indoor-cycles' },
      { id: 'hub', label: 'All Commercial Cardio', description: 'Browse the full commercial cardio hub', to: LANDING_PATHS.commercialCardio },
    ],
  },
  {
    id: 'used-commercial-indoor-cycles',
    path: '/used-commercial-indoor-cycles',
    cluster: 'commercial-cardio',
    parentPath: LANDING_PATHS.commercialCardio,
    parentName: 'Commercial Cardio Equipment',
    rating: C,
    categorySlugs: ['spin-bikes'],
    featuredBrandSlugs: brands(
      'technogym',
      'schwinn',
      'wattbike',
      'life-fitness',
      'matrix-fitness',
      'spirit-fitness',
      'peloton',
      'precor',
    ),
    neighborCategories: [
      { id: 'bikes', label: 'Commercial Exercise Bikes', description: 'Upright and recumbent bikes', to: '/used-commercial-exercise-bikes' },
      { id: 'tread', label: 'Commercial Treadmills', description: 'Facility-grade running decks', to: '/used-commercial-treadmills' },
      { id: 'rowers', label: 'Commercial Rowing Machines', description: 'Air, magnetic and water rowers', to: '/used-commercial-rowing-machines' },
      { id: 'cross', label: 'Commercial Cross Trainers', description: 'Ellipticals for high throughput', to: '/used-commercial-cross-trainers' },
      { id: 'stair', label: 'Commercial Stair Climbers', description: 'Stepmills and climbing cardio', to: '/used-commercial-stair-climbers' },
      { id: 'hub', label: 'All Commercial Cardio', description: 'Browse the full commercial cardio hub', to: LANDING_PATHS.commercialCardio },
    ],
  },
  {
    id: 'used-functional-trainers',
    path: '/used-functional-trainers',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['functional'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'technogym',
      'hammer-strength',
      'cybex',
      'matrix-fitness',
      'body-solid',
      'rogue-fitness',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'cable', label: 'Cable Machines', description: 'Dual pulley and cable stations', to: '/used-cable-machines' },
      { id: 'pin', label: 'Pin-Loaded Machines', description: 'Selectorised strength stations', to: '/used-pin-loaded-machines' },
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'rack', label: 'Power Racks', description: 'Commercial racks and cages', to: '/used-power-racks' },
      { id: 'bench', label: 'Commercial Benches', description: 'Flat, incline and adjustable', to: '/used-commercial-benches' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-smith-machines',
    path: '/used-smith-machines',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['plate-loaded-machine', 'squat-rack'],
    search: 'smith',
    searchIn: ['title', 'brand', 'model'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'hammer-strength',
      'technogym',
      'cybex',
      'matrix-fitness',
      'body-solid',
      'powertec',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'rack', label: 'Power Racks', description: 'Free-weight racks and cages', to: '/used-power-racks' },
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'leg', label: 'Leg Press Machines', description: 'Plate and selectorised leg press', to: '/used-leg-press-machines' },
      { id: 'bench', label: 'Commercial Benches', description: 'Flat, incline and adjustable', to: '/used-commercial-benches' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-power-racks',
    path: '/used-power-racks',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['squat-rack'],
    featuredBrandSlugs: brands(
      'rogue-fitness',
      'hammer-strength',
      'life-fitness',
      'eleiko',
      'rep',
      'body-solid',
      'powertec',
      'jordan',
    ),
    neighborCategories: [
      { id: 'smith', label: 'Smith Machines', description: 'Guided bar strength stations', to: '/used-smith-machines' },
      { id: 'bench', label: 'Commercial Benches', description: 'Flat, incline and adjustable', to: '/used-commercial-benches' },
      { id: 'db', label: 'Commercial Dumbbells', description: 'Fixed and pro-style sets', to: '/used-commercial-dumbbells' },
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-cable-machines',
    path: '/used-cable-machines',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['dual-cable-pulley'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'technogym',
      'cybex',
      'matrix-fitness',
      'hammer-strength',
      'body-solid',
      'pulse-fitness',
      'nautilus',
    ),
    neighborCategories: [
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'pin', label: 'Pin-Loaded Machines', description: 'Selectorised strength stations', to: '/used-pin-loaded-machines' },
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'rack', label: 'Power Racks', description: 'Commercial racks and cages', to: '/used-power-racks' },
      { id: 'bench', label: 'Commercial Benches', description: 'Flat, incline and adjustable', to: '/used-commercial-benches' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-leg-press-machines',
    path: '/used-leg-press-machines',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['plate-loaded-machine', 'pin-loaded-machine'],
    search: 'leg press',
    searchIn: ['title', 'brand', 'model'],
    excludeTitleIncludes: ['multi gym', 'multigym', 'multi-gym', 'home gym'],
    featuredBrandSlugs: brands(
      'hammer-strength',
      'life-fitness',
      'technogym',
      'cybex',
      'matrix-fitness',
      'body-solid',
      'nautilus',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'pin', label: 'Pin-Loaded Machines', description: 'Selectorised strength stations', to: '/used-pin-loaded-machines' },
      { id: 'smith', label: 'Smith Machines', description: 'Guided bar strength stations', to: '/used-smith-machines' },
      { id: 'rack', label: 'Power Racks', description: 'Commercial racks and cages', to: '/used-power-racks' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-plate-loaded-machines',
    path: '/used-plate-loaded-machines',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['plate-loaded-machine'],
    featuredBrandSlugs: brands(
      'hammer-strength',
      'life-fitness',
      'technogym',
      'cybex',
      'matrix-fitness',
      'body-solid',
      'powertec',
      'pulse-fitness',
    ),
    neighborCategories: [
      { id: 'pin', label: 'Pin-Loaded Machines', description: 'Selectorised strength stations', to: '/used-pin-loaded-machines' },
      { id: 'leg', label: 'Leg Press Machines', description: 'Plate and selectorised leg press', to: '/used-leg-press-machines' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'cable', label: 'Cable Machines', description: 'Dual pulley and cable stations', to: '/used-cable-machines' },
      { id: 'rack', label: 'Power Racks', description: 'Commercial racks and cages', to: '/used-power-racks' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-pin-loaded-machines',
    path: '/used-pin-loaded-machines',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['pin-loaded-machine'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'technogym',
      'cybex',
      'matrix-fitness',
      'nautilus',
      'body-solid',
      'pulse-fitness',
      'hammer-strength',
    ),
    neighborCategories: [
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'cable', label: 'Cable Machines', description: 'Dual pulley and cable stations', to: '/used-cable-machines' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'leg', label: 'Leg Press Machines', description: 'Plate and selectorised leg press', to: '/used-leg-press-machines' },
      { id: 'bench', label: 'Commercial Benches', description: 'Flat, incline and adjustable', to: '/used-commercial-benches' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-commercial-benches',
    path: '/used-commercial-benches',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['bench'],
    featuredBrandSlugs: brands(
      'life-fitness',
      'hammer-strength',
      'technogym',
      'rogue-fitness',
      'body-solid',
      'rep',
      'eleiko',
      'jordan',
    ),
    neighborCategories: [
      { id: 'rack', label: 'Power Racks', description: 'Commercial racks and cages', to: '/used-power-racks' },
      { id: 'db', label: 'Commercial Dumbbells', description: 'Fixed and pro-style sets', to: '/used-commercial-dumbbells' },
      { id: 'smith', label: 'Smith Machines', description: 'Guided bar strength stations', to: '/used-smith-machines' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'used-commercial-dumbbells',
    path: '/used-commercial-dumbbells',
    cluster: 'commercial-strength',
    parentPath: LANDING_PATHS.commercialStrength,
    parentName: 'Commercial Strength Equipment',
    rating: C,
    categorySlugs: ['dumbbells'],
    featuredBrandSlugs: brands(
      'eleiko',
      'rogue-fitness',
      'jordan',
      'hammer-strength',
      'life-fitness',
      'york-fitness',
      'rep',
      'body-solid',
    ),
    neighborCategories: [
      { id: 'bench', label: 'Commercial Benches', description: 'Flat, incline and adjustable', to: '/used-commercial-benches' },
      { id: 'rack', label: 'Power Racks', description: 'Commercial racks and cages', to: '/used-power-racks' },
      { id: 'plate', label: 'Plate-Loaded Machines', description: 'Hammer-style plate stations', to: '/used-plate-loaded-machines' },
      { id: 'func', label: 'Functional Trainers', description: 'Dual-cable functional stations', to: '/used-functional-trainers' },
      { id: 'pin', label: 'Pin-Loaded Machines', description: 'Selectorised strength stations', to: '/used-pin-loaded-machines' },
      { id: 'hub', label: 'All Commercial Strength', description: 'Browse the full strength hub', to: LANDING_PATHS.commercialStrength },
    ],
  },
  {
    id: 'home-treadmills',
    path: '/home-treadmills',
    cluster: 'home-cardio',
    parentPath: LANDING_PATHS.homeCardio,
    parentName: 'Home Cardio Equipment',
    rating: H,
    categorySlugs: ['treadmill'],
    featuredBrandSlugs: brands(
      'nordictrack',
      'sole-fitness',
      'horizon-fitness',
      'proform',
      'reebok',
      'york-fitness',
      'spirit-fitness',
      'bh-fitness',
    ),
    neighborCategories: [
      { id: 'bikes', label: 'Home Exercise Bikes', description: 'Upright, recumbent and spin bikes', to: '/home-exercise-bikes' },
      { id: 'cross', label: 'Home Cross Trainers', description: 'Ellipticals for home use', to: '/home-cross-trainers' },
      { id: 'rowers', label: 'Home Rowing Machines', description: 'Air, magnetic and water rowers', to: '/home-rowing-machines' },
      { id: 'hub', label: 'All Home Cardio', description: 'Browse the full home cardio hub', to: LANDING_PATHS.homeCardio },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Treadmills', description: 'Facility-grade running decks', to: '/used-commercial-treadmills' },
    ],
  },
  {
    id: 'home-exercise-bikes',
    path: '/home-exercise-bikes',
    cluster: 'home-cardio',
    parentPath: LANDING_PATHS.homeCardio,
    parentName: 'Home Cardio Equipment',
    rating: H,
    categorySlugs: ['upright-bikes', 'recumbent-bikes', 'spin-bikes'],
    featuredBrandSlugs: brands(
      'nordictrack',
      'proform',
      'schwinn',
      'bowflex',
      'horizon-fitness',
      'sole-fitness',
      'reebok',
      'peloton',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Home Treadmills', description: 'Folding and compact running decks', to: '/home-treadmills' },
      { id: 'cross', label: 'Home Cross Trainers', description: 'Ellipticals for home use', to: '/home-cross-trainers' },
      { id: 'rowers', label: 'Home Rowing Machines', description: 'Air, magnetic and water rowers', to: '/home-rowing-machines' },
      { id: 'hub', label: 'All Home Cardio', description: 'Browse the full home cardio hub', to: LANDING_PATHS.homeCardio },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Exercise Bikes', description: 'Facility-grade upright and recumbent', to: '/used-commercial-exercise-bikes' },
    ],
  },
  {
    id: 'home-cross-trainers',
    path: '/home-cross-trainers',
    cluster: 'home-cardio',
    parentPath: LANDING_PATHS.homeCardio,
    parentName: 'Home Cardio Equipment',
    rating: H,
    categorySlugs: ['crosstrainers'],
    featuredBrandSlugs: brands(
      'nordictrack',
      'proform',
      'horizon-fitness',
      'sole-fitness',
      'reebok',
      'spirit-fitness',
      'bh-fitness',
      'york-fitness',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Home Treadmills', description: 'Folding and compact running decks', to: '/home-treadmills' },
      { id: 'bikes', label: 'Home Exercise Bikes', description: 'Upright, recumbent and spin bikes', to: '/home-exercise-bikes' },
      { id: 'rowers', label: 'Home Rowing Machines', description: 'Air, magnetic and water rowers', to: '/home-rowing-machines' },
      { id: 'hub', label: 'All Home Cardio', description: 'Browse the full home cardio hub', to: LANDING_PATHS.homeCardio },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Cross Trainers', description: 'Facility-grade ellipticals', to: '/used-commercial-cross-trainers' },
    ],
  },
  {
    id: 'home-rowing-machines',
    path: '/home-rowing-machines',
    cluster: 'home-cardio',
    parentPath: LANDING_PATHS.homeCardio,
    parentName: 'Home Cardio Equipment',
    rating: H,
    categorySlugs: ['rowers'],
    featuredBrandSlugs: brands(
      'concept2',
      'waterrower',
      'nordictrack',
      'proform',
      'bowflex',
      'horizon-fitness',
      'sole-fitness',
      'york-fitness',
    ),
    neighborCategories: [
      { id: 'tread', label: 'Home Treadmills', description: 'Folding and compact running decks', to: '/home-treadmills' },
      { id: 'bikes', label: 'Home Exercise Bikes', description: 'Upright, recumbent and spin bikes', to: '/home-exercise-bikes' },
      { id: 'cross', label: 'Home Cross Trainers', description: 'Ellipticals for home use', to: '/home-cross-trainers' },
      { id: 'hub', label: 'All Home Cardio', description: 'Browse the full home cardio hub', to: LANDING_PATHS.homeCardio },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Rowing Machines', description: 'Facility-grade rowers', to: '/used-commercial-rowing-machines' },
    ],
  },
  {
    id: 'home-multi-gyms',
    path: '/home-multi-gyms',
    cluster: 'home-strength',
    parentPath: LANDING_PATHS.homeStrength,
    parentName: 'Home Strength Equipment',
    rating: H,
    categorySlugs: ['multi-gyms'],
    featuredBrandSlugs: brands(
      'body-solid',
      'bowflex',
      'york-fitness',
      'powertec',
      'nautilus',
      'proform',
      'bh-fitness',
      'reebok',
    ),
    neighborCategories: [
      { id: 'db', label: 'Home Dumbbells', description: 'Fixed and adjustable sets', to: '/home-dumbbells' },
      { id: 'bench', label: 'Home Weight Benches', description: 'Flat, incline and folding', to: '/home-weight-benches' },
      { id: 'rack', label: 'Home Power Racks', description: 'Garage and spare-room racks', to: '/home-power-racks' },
      { id: 'hub', label: 'All Home Strength', description: 'Browse the full home strength hub', to: LANDING_PATHS.homeStrength },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'func', label: 'Functional Trainers', description: 'Commercial dual-cable stations', to: '/used-functional-trainers' },
    ],
  },
  {
    id: 'home-dumbbells',
    path: '/home-dumbbells',
    cluster: 'home-strength',
    parentPath: LANDING_PATHS.homeStrength,
    parentName: 'Home Strength Equipment',
    rating: H,
    categorySlugs: ['dumbbells'],
    featuredBrandSlugs: brands(
      'bowflex',
      'york-fitness',
      'rogue-fitness',
      'eleiko',
      'jordan',
      'body-solid',
      'reebok',
      'rep',
    ),
    neighborCategories: [
      { id: 'bench', label: 'Home Weight Benches', description: 'Flat, incline and folding', to: '/home-weight-benches' },
      { id: 'rack', label: 'Home Power Racks', description: 'Garage and spare-room racks', to: '/home-power-racks' },
      { id: 'multi', label: 'Home Multi Gyms', description: 'All-in-one strength stations', to: '/home-multi-gyms' },
      { id: 'hub', label: 'All Home Strength', description: 'Browse the full home strength hub', to: LANDING_PATHS.homeStrength },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Dumbbells', description: 'Facility-grade free weights', to: '/used-commercial-dumbbells' },
    ],
  },
  {
    id: 'home-weight-benches',
    path: '/home-weight-benches',
    cluster: 'home-strength',
    parentPath: LANDING_PATHS.homeStrength,
    parentName: 'Home Strength Equipment',
    rating: H,
    categorySlugs: ['bench'],
    featuredBrandSlugs: brands(
      'body-solid',
      'bowflex',
      'york-fitness',
      'rogue-fitness',
      'rep',
      'powertec',
      'proform',
      'reebok',
    ),
    neighborCategories: [
      { id: 'db', label: 'Home Dumbbells', description: 'Fixed and adjustable sets', to: '/home-dumbbells' },
      { id: 'rack', label: 'Home Power Racks', description: 'Garage and spare-room racks', to: '/home-power-racks' },
      { id: 'multi', label: 'Home Multi Gyms', description: 'All-in-one strength stations', to: '/home-multi-gyms' },
      { id: 'hub', label: 'All Home Strength', description: 'Browse the full home strength hub', to: LANDING_PATHS.homeStrength },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Benches', description: 'Facility-grade benches', to: '/used-commercial-benches' },
    ],
  },
  {
    id: 'home-power-racks',
    path: '/home-power-racks',
    cluster: 'home-strength',
    parentPath: LANDING_PATHS.homeStrength,
    parentName: 'Home Strength Equipment',
    rating: H,
    categorySlugs: ['squat-rack'],
    featuredBrandSlugs: brands(
      'rogue-fitness',
      'rep',
      'body-solid',
      'york-fitness',
      'powertec',
      'eleiko',
      'bowflex',
      'jordan',
    ),
    neighborCategories: [
      { id: 'bench', label: 'Home Weight Benches', description: 'Flat, incline and folding', to: '/home-weight-benches' },
      { id: 'db', label: 'Home Dumbbells', description: 'Fixed and adjustable sets', to: '/home-dumbbells' },
      { id: 'multi', label: 'Home Multi Gyms', description: 'All-in-one strength stations', to: '/home-multi-gyms' },
      { id: 'hub', label: 'All Home Strength', description: 'Browse the full home strength hub', to: LANDING_PATHS.homeStrength },
      { id: 'home', label: 'Home Gym Equipment', description: 'All home fitness equipment', to: LANDING_PATHS.homeGym },
      { id: 'comm', label: 'Commercial Power Racks', description: 'Facility-grade racks', to: '/used-power-racks' },
    ],
  },
]

export const EQUIPMENT_LANDING_DEFS_VALIDATED = Object.freeze(
  RAW_DEFS.map((def) =>
    Object.freeze({
      ...def,
      categorySlugs: Object.freeze(def.categorySlugs || []),
      searchIn: def.searchIn ? Object.freeze(def.searchIn) : undefined,
      excludeTitleIncludes: def.excludeTitleIncludes
        ? Object.freeze(def.excludeTitleIncludes)
        : undefined,
      featuredBrandSlugs: def.featuredBrandSlugs,
      neighborCategories: Object.freeze(def.neighborCategories || []),
    }),
  ),
)

/** @deprecated alias — prefer EQUIPMENT_LANDING_DEFS_VALIDATED */
export const EQUIPMENT_LANDING_DEFS = EQUIPMENT_LANDING_DEFS_VALIDATED

export const EQUIPMENT_LANDING_PATHS = Object.freeze(
  EQUIPMENT_LANDING_DEFS_VALIDATED.map((def) => def.path),
)

export const EQUIPMENT_LANDING_PATH_SET = new Set(EQUIPMENT_LANDING_PATHS)

export function getEquipmentLandingDef(idOrPath) {
  return (
    EQUIPMENT_LANDING_DEFS_VALIDATED.find(
      (def) => def.id === idOrPath || def.path === idOrPath,
    ) || null
  )
}
